### ISSUE TITLE
Converting of YAML to TSV fails

### ISSUE THREAD

**Issue by Athemis** [HenningTimm/yml2block#16]
Converting a YAML file to TSV fails, if no warnings are raised.

```
python __main__.py convert ../tests/valid/minimal_working_example.yml -o ../tests/valid/minimal_working_example.tsv
Traceback (most recent call last):
  File "/home/user/git/yml2block/yml2block/__main__.py", line 276, in <module>
    main()
  File "/home/user/software/yml2block/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/software/yml2block/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/software/yml2block/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/software/yml2block/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/software/yml2block/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git/yml2block/yml2block/__main__.py", line 265, in convert
    if input_type == "yaml" and lint_violations.safe_conversion_possible(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/git/yml2block/yml2block/__main__.py", line 59, in safe_conversion_possible
    max_severity = min(self.violations[file_path], key=lambda x: x.level).level
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() iterable argument is empty
```
A YAML that generates at least one warning however **is** converted if strict mode is not used.

**Comment by HenningTimm** [comment]
Well, this is embarrassing. Apparently success was never an option. Thanks for pointing this out!
