### ISSUE TITLE
Error if watermark contains only numbers

### ISSUE THREAD

**Issue by Athemis** [HenningTimm/yml2block#19]
If the a watermark for a data field is defined that only consists of numbers (e.g. '3776') the following error occurs. Just appending a single letter to the number circumvents the issue. This is probably caused by implicit conversion to `int` while the regex can only work on strings. 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cbm343e/.cache/pypoetry/virtualenvs/yml2block-ivYprUlk-py3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm343e/.cache/pypoetry/virtualenvs/yml2block-ivYprUlk-py3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/cbm343e/.cache/pypoetry/virtualenvs/yml2block-ivYprUlk-py3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm343e/.cache/pypoetry/virtualenvs/yml2block-ivYprUlk-py3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm343e/.cache/pypoetry/virtualenvs/yml2block-ivYprUlk-py3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm343e/repos/yml2block/yml2block/__main__.py", line 193, in check
    _data, _longest_row, file_lint_violations = yaml_input.read_yaml(
                                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm343e/repos/yml2block/yml2block/yaml_input.py", line 42, in read_yaml
    longest_row, file_lint_violations = validation.validate_yaml(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm343e/repos/yml2block/yml2block/validation.py", line 14, in validate_yaml
    block_row_max, entry_violations = validate_entry(
                                      ^^^^^^^^^^^^^^^
  File "/home/cbm343e/repos/yml2block/yml2block/validation.py", line 84, in validate_entry
    violations.extend(lint(item, tsv_keyword))
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cbm343e/repos/yml2block/yml2block/rules.py", line 441, in no_trailing_spaces
    if value and re.search(" +$", value):
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/re/__init__.py", line 177, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'int'

```

**Comment by HenningTimm** [comment]
Thank you for fixing this!
